name: 'Pop Linux build' 
inputs:
  lib_dir:
    required: false
  os: 
    required: true
  project:
    required: true
  arch:
    required: false
  flag:
    required: false
runs:
  using: 'node12'
  main: 'index.js'
