name: 'Pop Linux build' 
inputs:
  machine:
    required: true
  architecture: 
    required: true
  project:
    required: true
  UploadArtifact:
    required: false
    default: true
runs:
  using: 'node12'
  main: 'index.js'
